//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAdjunto
    {
        public int Id { get; set; }
        public Nullable<int> IdContenido { get; set; }
        public string RutaAdjunto { get; set; }
        public string Nombre { get; set; }
    
        public virtual tbContenido tbContenido { get; set; }
    }
}
