//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAdjuntoPasoAmbiente
    {
        public int Id { get; set; }
        public Nullable<int> IdPaso { get; set; }
        public string Ruta { get; set; }
        public string NombreArchivo { get; set; }
    
        public virtual tbPasoAmbiente tbPasoAmbiente { get; set; }
    }
}
