//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbApoyoPasoAmbiente
    {
        public int Id { get; set; }
        public Nullable<int> IdPasoAmbiente { get; set; }
        public Nullable<int> IdArea { get; set; }
        public string PersonaApoyo { get; set; }
        public string TelefonoContacto { get; set; }
    
        public virtual tbAreaApoyo tbAreaApoyo { get; set; }
        public virtual tbPasoAmbiente tbPasoAmbiente { get; set; }
    }
}
