//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbIniciativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbIniciativa()
        {
            this.tbCategoriaHD = new HashSet<tbCategoriaHD>();
            this.tbTema = new HashSet<tbTema>();
            this.tbPasoAmbiente = new HashSet<tbPasoAmbiente>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdProyecto { get; set; }
        public string Nombre { get; set; }
        public string PMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCategoriaHD> tbCategoriaHD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTema> tbTema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPasoAmbiente> tbPasoAmbiente { get; set; }
        public virtual tbProyecto tbProyecto { get; set; }
    }
}
