//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPasoAmbiente
    {
        public int Id { get; set; }
        public Nullable<int> IdAplicacion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Ambiente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NumeroOC { get; set; }
        public string Resultado { get; set; }
        public string Harvest { get; set; }
        public string RutaAdjunto { get; set; }
    
        public virtual tbAplicacion tbAplicacion { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
