//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSubCategoriaHD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSubCategoriaHD()
        {
            this.tbItemSubcategoria = new HashSet<tbItemSubcategoria>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Nombre { get; set; }
    
        public virtual tbCategoriaHD tbCategoriaHD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbItemSubcategoria> tbItemSubcategoria { get; set; }
    }
}
